server:
  port: 8761 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（默认true）
    register-with-eureka: false #指定是否要注册到注册中心（默认true）
  server:
    enable-self-preservation: false #是否开启保护模式（默认true）
    eviction-interval-timer-in-ms: 3000 # 清理间隔（单位毫秒，默认是60*1000）

logging:
  level:
    com.netflix: warn