spring:
  application:
    name: upload
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
server:
  port: 8083 #运行端口号
eureka:
  instance:
    hostname: localhost #指定主机地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://localhost:8761/eureka #配置注册中心地址
    registry-fetch-interval-seconds: 10 # 设置服务消费者从注册中心拉取服务列表的间隔
# Ribbon的常用配置
ribbon:
  ConnectTimeout: 1000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 5000 #服务请求处理超时时间（毫秒）
  OkToRetryOnAllOperations: false #对超时请求启用重试机制
  MaxAutoRetriesNextServer: 0 #切换重试实例的最大个数
  MaxAutoRetries: 0 # 切换实例后重试最大次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
