
spring:
  application:
    name: zuul-proxy   #服务名
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  #设置链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #设置Sleuth的抽样收集概率
server:
  port: 11111   # 端口

#注册中心相关配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

#网关配置
zuul:

  prefix: /api/      #前缀
  routes:   #路由规则
    user:
      path: /u/**
    team:
      path: /t/**
    product:
      path: /p/**
    news:
      path: /n/**
    auth:
      path: /a/**
    code:
      path: /code/**
    upload:
      path: /upload/**


  # 关闭那些服务的默认路由
  ignored-services: '*'

  add-host-header: true
  #不对敏感资源做拦截
  sensitive-headers:
  ignored-headers:
  host:
    socket-timeout-millis: 4000 # 请求的处理时间
    connect-timeout-millis: 4000 # 请求的链接时间
#开启路由端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'

logging:
  level:
    #com.netflix: warn
    com.wx.zuul.feign: debug

jwt:
  #定义我们的盐  密码
  secret: mySecret
  #过期时间
  expiration: 18000
  #token 的类型 说明他以 bearer 开头
  tokenHead: bearer
  #token 对应的 key
  tokenHeader: Authorization
#  {Authorization: "bearer sdfdsfsdfsdfdsfsdfadfdsf"}

pathList: 'user/,code/,product/,news/,upload,team/'
ribbon:
  ConnectTimeot: 60000 # 连接超时时间（ms）
  ReadTimeot: 60000 # 通信超时时间（ms）
  OkToRertryOnAllOperations: ture # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 #同一个服务不同实例的重试次数
  MaxAutoRetries: 1 #同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 60000 #熔断超时时长 10000ms

